"""Regenerating the Net Surplus Compensation rate series.

Published as a standing table of one rate per true-up month, rather than as part
of a tariff sheet::

    True-up Month  NSC Rate* ($/kWh)
    Jan. 2025      0.03396
    Feb. 2025      0.03087

It grows by a row a month, which is exactly the shape that goes stale quietly:
nothing about a missing month looks wrong until a true-up lands in it. The
annual true-up reads this series, so it needs the same weekly check as the rest.

Note what this rate is *not*. Schedule NBT limits Net Surplus Compensation to
bundled customers -- a CCA account is barred outright -- so for a CCA account
this series is a documented stand-in and never the rate that gets paid. See
:mod:`tariffkit.billing.trueup`.
"""

from __future__ import annotations

import re
from datetime import date

from .emit import DATA_DIR, Result, write_or_check
from .providers import Utility
from .sheets import ExtractionError, Page, cells

#: The heading that identifies the table.
TABLE_HEADING = "Net Surplus Compensation Rates"

#: "Jan. 2025 0.03396" -- an abbreviated or full month, a year, then the rate.
MONTHS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}
ROW = re.compile(r"^([A-Z][a-z]{2})[a-z]*\.?\s+(\d{4})\b(.*)$")

#: The series has moved between 0.026 and 0.034. An order of magnitude out means
#: a figure was picked up from the footnote rather than the table.
PLAUSIBLE = (0.001, 0.5)

#: Fewer rows than this and the table was truncated by a bad parse.
MIN_MONTHS = 6


def extract(pages: list[Page]) -> dict[str, float]:
    """``{"YYYY-MM": rate}`` for every published true-up month."""
    if not any(TABLE_HEADING in page.text for page in pages):
        raise ExtractionError(f"no page contains {TABLE_HEADING!r}")

    found: dict[str, float] = {}
    for page in pages:
        for raw in page.text.splitlines():
            line = raw.strip().rstrip("|").strip()
            match = ROW.match(line)
            if not match:
                continue
            month = MONTHS.get(match.group(1).lower())
            values = cells(match.group(3))
            if month is None or not values:
                continue
            rate = values[0]
            if not PLAUSIBLE[0] <= rate <= PLAUSIBLE[1]:
                raise ExtractionError(
                    f"{match.group(1)} {match.group(2)}: {rate} is outside the "
                    f"plausible range {PLAUSIBLE}"
                )
            found[f"{int(match.group(2)):04d}-{month:02d}"] = rate

    if len(found) < MIN_MONTHS:
        raise ExtractionError(f"found only {len(found)} NSC months; expected at least {MIN_MONTHS}")
    return found


def verify_against_library(body: str, extracted: dict[str, float]) -> list[str]:
    """Every month written must be readable by the code that consumes it."""
    import tomllib
    import unittest.mock

    from tariffkit.billing import trueup

    raw = tomllib.loads(body)
    problems: list[str] = []
    if set(raw.get("rates", {})) != set(extracted):
        problems.append("the rendered [rates] table does not match what was extracted")
        
    def mock_read_data_text(relative: str) -> str:
        if relative == trueup.NSC_RATE_FILE:
            return body
        from tariffkit.data import read_data_text
        return read_data_text(relative)

    with unittest.mock.patch("tariffkit.billing.trueup.read_data_text", side_effect=mock_read_data_text):
        for key, value in sorted(extracted.items()):
            year, month = (int(p) for p in key.split("-"))
            try:
                got = trueup.published_nsc_rate(date(year, month, 15))
            except Exception as exc:
                problems.append(f"{key}: the library could not read it back: {exc}")
                break
            if abs(got - value) > 1e-9:
                problems.append(f"{key}: library reads {got}, extracted {value}")
    return problems


def render(provider: Utility, rates: dict[str, float], source_url: str) -> str:
    latest = max(rates)
    return (
        "\n".join(
            [
                f"# {provider.name} Net Surplus Compensation (NSC) rates, by true-up month.",
                "#",
                f"# Source: {source_url}",
                "#",
                "# GENERATED by `python -m tools.regen nsc` -- do not hand-edit.",
                "#",
                "# Definition, from the table's own footnote: per D.11-06-016, the",
                "# electricity portion of the NSC rate is the simple rolling average of the",
                "# utility's default load aggregation point price from 7 a.m. to 5 p.m.,",
                "# corresponding to the customer's 12-month true-up period. Schedule NBT",
                "# adds the mechanics: the rate is calculated monthly, effective the first",
                "# of that month, and applies to any Net Surplus Generator whose Relevant",
                "# Period completed in it.",
                "#",
                "# READ THIS BEFORE USING IT FOR A CCA ACCOUNT. Schedule NBT, Special",
                "# Condition 5.a bars net surplus generators taking Direct Access or",
                "# Community Choice Aggregation service from receiving NSC from the utility,",
                "# and applicability is limited to bundled generators. For a CCA account",
                "# this table is NOT the rate that will be paid -- the CCA's own tariff",
                "# governs, and MCE determines its rate at cash-out rather than publishing",
                "# it ahead. It is vendored because it is the only published, auditable NSC",
                "# series there is, which makes it a usable stand-in until a real cash-out",
                "# statement exists. Anything computed from it for a CCA account is an",
                "# estimate and is flagged as one.",
                "#",
                f"# A row is added each month; the series here ends at {latest}. A true-up",
                "# month later than that has no published rate yet, which is the normal",
                "# case rather than an edge one.",
                "",
                "schema = 1",
                f'utility = "{provider.identifier}"',
                'currency = "USD/kWh"',
                f'source_url = "{source_url}"',
                'decision = "D.11-06-016"',
                "",
                "# Keyed by true-up month: the month in which a Relevant Period completes.",
                "[rates]",
                *[f'"{k}" = {v:.5f}' for k, v in sorted(rates.items())],
            ]
        )
        + "\n"
    )


def regenerate(provider: Utility, pdf: object, *, check: bool) -> Result:
    from pathlib import Path

    from .sheets import read_pages

    if provider.nsc_rates is None:
        raise ExtractionError(f"{provider.key} publishes no NSC rate table")
    rates = extract(read_pages(Path(str(pdf))))
    body = render(provider, rates, provider.nsc_rates.url)
    return write_or_check(
        f"{provider.key}/nsc",
        DATA_DIR / "nsc" / f"{provider.key}.toml",
        body,
        check=check,
        verify=lambda text: verify_against_library(text, rates),
        messages=[f"{len(rates)} true-up months, {min(rates)} to {max(rates)}"],
    )
