"""Regenerate residential overlay rates from their tariff schedules."""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from .emit import DATA_DIR, Result, fmt, write_or_check
from .providers import Program
from .sheets import ExtractionError, Page, read_pages


def _effective(pages: list[Page], marker: str) -> tuple[date, str]:
    page = next((item for item in pages if marker in item.text), None)
    if page is None or page.effective is None or page.advice_letter is None:
        raise ExtractionError(f"the page containing {marker!r} has no effective provenance")
    return page.effective, page.advice_letter


def _percent(text: str, pattern: str) -> float:
    match = re.search(pattern, text, re.I)
    if match is None:
        raise ExtractionError(f"published overlay rate not found: {pattern}")
    return float(match.group(1)) / 100


def _money(text: str, pattern: str) -> float:
    match = re.search(pattern, text, re.I | re.S)
    if match is None:
        raise ExtractionError(f"published overlay rate not found: {pattern}")
    return float(match.group(1))


def extract(provider: Program, pages: list[Page]) -> tuple[date, str, dict[str, object]]:
    text = "\n".join(page.text for page in pages)
    if provider.key == "dcare":
        effective, advice = _effective(pages, "ELECTRIC SCHEDULE D-CARE Sheet 2")
        return (
            effective,
            advice,
            {
                "discount": _percent(text, r"D-CARE Discount:\s+([0-9.]+)\s+%"),
                "eligible_schedules": ["E-1", "E-ELEC", "E-TOU-C", "E-TOU-D", "EV2-A"],
                "exempt_components": [
                    "wildfire_fund_charge",
                    "wildfire_hardening",
                    "recovery_bond_charge",
                    "recovery_bond_credit",
                ],
            },
        )
    if provider.key == "efera":
        effective, advice = _effective(pages, "ELECTRIC SCHEDULE E-FERA Sheet 1")
        return (
            effective,
            advice,
            {
                "discount": _percent(text, r"receive an\s+([0-9.]+)\s+percent discount"),
                "eligible_schedules": ["E-1", "E-ELEC", "E-TOU-C", "E-TOU-D", "EV2-A"],
                # E-FERA sheet 1: "after FERA customers are exempted from the
                # Wildfire Hardening Charge, Recovery Bond Charge, and the
                # Recovery Bond Credit." Three, not D-CARE's four -- FERA is
                # NOT exempt from the Wildfire Fund Charge.
                "exempt_components": [
                    "wildfire_hardening",
                    "recovery_bond_charge",
                    "recovery_bond_credit",
                ],
            },
        )
    if provider.key == "dmedical":
        effective, advice = _effective(pages, "ELECTRIC SCHEDULE D-MEDICAL Sheet 1")
        return (
            effective,
            advice,
            {
                "discount": _percent(text, r"receive a\s+([0-9.]+)\s+percent discount"),
                "eligible_schedules": ["E-ELEC", "E-TOU-D", "EV2-A"],
                "exempt_components": ["wildfire_fund_charge"],
            },
        )
    if provider.key == "medicalbaseline":
        effective, advice = _effective(pages, "ELECTRIC RULE NO. 19 Sheet 1")
        return (
            effective,
            advice,
            {
                "eligible_schedules": ["E-1", "E-TOU-C"],
                "standard_kwh_per_year": 6000,
            },
        )
    if provider.key == "ersmart":
        effective, advice = _effective(pages, "ELECTRIC SCHEDULE E-RSMART Sheet 2")
        return (
            effective,
            advice,
            {
                "eligible_schedules": ["E-1", "E-ELEC", "E-TOU-C", "E-TOU-D", "EV2-A"],
                "high_price_charge": _money(text, r"High Price\s+Period Usage\s+\$([0-9.]+)"),
                "program_credit": _money(
                    text,
                    r"All Non-High-\s+Price Period.*?\(\$([0-9.]+)\)",
                ),
                "participation_credit": _money(
                    text,
                    r"All Non-High-\s+Price Period.*?\(\$[0-9.]+\).*?\(\$([0-9.]+)\)",
                ),
                "high_price_start": 16,
                "high_price_end": 21,
                "minimum_events": 9,
                "maximum_events": 15,
            },
        )
    raise ExtractionError(f"no residential-program extractor for {provider.key}")


def render(
    provider: Program,
    effective: date,
    advice: str,
    values: dict[str, object],
) -> str:
    lines = [
        f"# PG&E residential program {provider.key}.",
        "#",
        f"# Source: {provider.source.url}",
        "# GENERATED by `python -m tools.regen program` -- do not hand-edit.",
        "",
        "schema = 1",
        f'utility = "{provider.utility}"',
        f'program = "{provider.key}"',
        f'effective = "{effective.isoformat()}"',
        f'advice_letter = "{advice}"',
        f'source_url = "{provider.source.url}"',
    ]
    for key, value in values.items():
        lines.append(f"{key} = {fmt(value)}")
    return "\n".join(lines) + "\n"


def regenerate(provider: Program, pdf: Path, *, check: bool) -> Result:
    effective, advice, values = extract(provider, read_pages(pdf))
    body = render(provider, effective, advice, values)
    path = DATA_DIR / "tariff" / provider.data_slug / "program" / provider.key
    return write_or_check(
        f"{provider.data_slug}/{provider.key}",
        path / f"{effective.isoformat()}.toml",
        body,
        check=check,
    )
