"""Regenerating a state surcharge that is not a utility tariff.

California's Energy Resources (Electrical Energy) Surcharge is imposed on energy
consumed in the state, whoever supplies it, so it is neither a utility's tariff
nor a CCA's rate card -- and it is billed on whichever page the generation
provider owns. On a CCA account that is the CCA's page, which is how it went
unmodelled while every line on the utility's pages reconciled to the cent.

The California Energy Commission sets it each November for the following
calendar year, and CDTFA publishes the result as a numbered notice::

    2026 Energy Resources (Electrical Energy) Surcharge Rate
    The California Energy Commission (CEC) set the electrical energy surcharge
    rate for the 2026 calendar year to remain at three-tenths mill ($.0003) per
    kilowatt-hour.

One number in one sentence, which makes the parsing easy and the *finding* the
part worth automating: CDTFA now issues a notice only when the rate changes, so
there is no notice for a year that carried forward, and a missing notice is a
normal answer rather than a failure.
"""

from __future__ import annotations

import re
from datetime import date

from .emit import DATA_DIR, Result, write_or_check
from .providers import Tax
from .sheets import ExtractionError, Page, read_pages

#: "for the 2026 calendar year" -- which year the notice sets.
YEAR = re.compile(r"for the\s+(20\d{2})\s+calendar year", re.I)
#: "($.0003) per kilowatt-hour" -- the rate itself, in dollars.
RATE = re.compile(r"\(\$?\s*(\.\d+|\d*\.\d+)\s*\)\s*per\s+kilowatt", re.I)

#: The surcharge has been three-tenths of a mill for years. An order of
#: magnitude either side means a figure came from an address or a phone number.
PLAUSIBLE = (0.00001, 0.01)


def extract(pages: list[Page]) -> tuple[int, float]:
    """``(calendar year, rate per kWh)`` from a CDTFA surcharge notice."""
    text = " ".join(page.text for page in pages)
    year = YEAR.search(text)
    rate = RATE.search(text)
    if not year or not rate:
        raise ExtractionError(
            "this notice does not state a calendar year and a per-kilowatt-hour rate "
            "in the expected form; CDTFA may have reworded it"
        )
    value = float(rate.group(1))
    if not PLAUSIBLE[0] <= value <= PLAUSIBLE[1]:
        raise ExtractionError(f"surcharge {value} is outside the plausible range {PLAUSIBLE}")
    return int(year.group(1)), value


def verify_against_library(body: str, year: int, rate: float) -> list[str]:
    """The rendered file must say what was extracted, in the shape data expects.

    Checked against the rendered text rather than against what is on disk. The
    first vintage of a dataset has nothing on disk yet, and a check that could
    only pass once a file existed would refuse to create it -- which is exactly
    what it did.
    """
    import tomllib

    from tariffkit.data.versioned import Version

    raw = tomllib.loads(body)
    problems: list[str] = []
    if abs(float(raw.get("rate", 0.0)) - rate) > 1e-12:
        problems.append(f"rendered rate {raw.get('rate')!r} is not the extracted {rate}")
    if str(raw.get("effective", "")) != f"{year}-01-01":
        problems.append(f"rendered effective {raw.get('effective')!r} is not {year}-01-01")
    try:
        # The same construction versioned.load performs when reading a vintage.
        Version(date.fromisoformat(str(raw["effective"])), raw)
    except (KeyError, ValueError) as exc:
        problems.append(f"the rendered file is not loadable as a vintage: {exc}")
    return problems


def render(provider: Tax, year: int, rate: float, notice: str) -> str:
    return (
        "\n".join(
            [
                f"# {provider.name}.",
                "#",
                f"# Source: CDTFA notice {notice}",
                f"#   {provider.url_for(notice)}",
                "#",
                "# GENERATED by `python -m tools.regen tax` -- do not hand-edit.",
                "#",
                "# A state surcharge on electrical energy consumed, not a utility tariff: it",
                "# is imposed whoever supplies the generation, so it applies to a CCA and a",
                '# bundled account alike. A statement prints it as "Energy Commission Tax",',
                "# and when a CCA supplies generation it prints on their page rather than the",
                "# utility's -- which is how it can go unnoticed while every line on the",
                "# utility's pages reconciles.",
                "#",
                "# The California Energy Commission sets it each November for the following",
                "# calendar year, so vintages are calendar-yearly. CDTFA issues a notice only",
                "# when the rate changes, so a year without one carries the previous rate --",
                "# which dated-vintage resolution already expresses.",
                "",
                "schema = 1",
                f'jurisdiction = "{provider.jurisdiction}"',
                f'effective = "{year}-01-01"',
                'unit = "USD/kWh"',
                f'source_url = "{provider.url_for(notice)}"',
                f'notice = "{notice.upper()}"',
                "",
                f"rate = {rate:.5f}",
            ]
        )
        + "\n"
    )


def regenerate(provider: Tax, pdf: object, *, check: bool, notice: str = "") -> Result:
    from pathlib import Path

    year, rate = extract(read_pages(Path(str(pdf))))
    body = render(provider, year, rate, notice or provider.latest_notice)
    return write_or_check(
        f"{provider.key} {year}",
        DATA_DIR / "tax" / provider.key / f"{year}-01-01.toml",
        body,
        check=check,
        verify=lambda text: verify_against_library(text, year, rate),
        messages=[f"{year} calendar year, {rate} per kWh"],
    )
